---
title: "Wild git collaboration practice!"
author: "Dina and Casey"
date: "1/25/2022"
output: html_document
---

```{r setup, include=TRUE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## STEP 4: No merge conflicts!

```{r partner 1}
ggplot(diamonds, aes(x = carat, y = price)) +
  geom_point(aes(color = cut)) +
  theme_minimal()
```

```{r partner 2}
### In this code chunk, start with the diamonds dataset (built in to
### ggplot2 package) and create a subset based on filtering, e.g., 
### size greater than 1 carat or cut is "Ideal"

data(diamonds)
data <- diamonds 

subset <- data %>% 
  filter(carat > 1)

summary(subset)

```

## STEP 7: Uh oh, merge conflicts!

```{r break-it-1}
diamonds_subset <- diamonds %>%
  filter(price > 5000 & cut == 'Ideal')

psych::describe(subset)
```

## STEP 10: And even more merge conflicts!

```{r break-it-2}
### Both partners - delete this comment, then write some code here
### to plot, summarize, calculate something simple using the diamonds
### dataset.


```
